// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAafHRuWR6F5EZqPmnNY2sC04VjhC6qjeg',
    appId: '1:241299853899:web:d8402d526c3ba36882b3ce',
    messagingSenderId: '241299853899',
    projectId: 'todoapp-60fce',
    authDomain: 'todoapp-60fce.firebaseapp.com',
    storageBucket: 'todoapp-60fce.appspot.com',
    measurementId: 'G-L1237QX3FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc6iwnCMB84D7JCyYhoEVfcqcz_dV29gA',
    appId: '1:241299853899:android:14e9ef016af6278182b3ce',
    messagingSenderId: '241299853899',
    projectId: 'todoapp-60fce',
    storageBucket: 'todoapp-60fce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkxg67mlvpL5yE9ha6d864B3_s7VUORLQ',
    appId: '1:241299853899:ios:812bf514107fc60e82b3ce',
    messagingSenderId: '241299853899',
    projectId: 'todoapp-60fce',
    storageBucket: 'todoapp-60fce.appspot.com',
    iosBundleId: 'com.wecodelife.todolist.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkxg67mlvpL5yE9ha6d864B3_s7VUORLQ',
    appId: '1:241299853899:ios:812bf514107fc60e82b3ce',
    messagingSenderId: '241299853899',
    projectId: 'todoapp-60fce',
    storageBucket: 'todoapp-60fce.appspot.com',
    iosBundleId: 'com.wecodelife.todolist.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAafHRuWR6F5EZqPmnNY2sC04VjhC6qjeg',
    appId: '1:241299853899:web:5df374c2b060d1bc82b3ce',
    messagingSenderId: '241299853899',
    projectId: 'todoapp-60fce',
    authDomain: 'todoapp-60fce.firebaseapp.com',
    storageBucket: 'todoapp-60fce.appspot.com',
    measurementId: 'G-BTT7V27X7C',
  );
}
